# Generated by Django 4.2.7 on 2026-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('dimensions', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
                ('page', models.IntegerField(default=1)),
                ('is_landscape', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
